# Generated by Django 4.1.4 on 2022-12-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('validity', models.IntegerField(choices=[('28', 'month pack'), ('56', 'two months pack'), ('84', 'three months pack'), ('180', 'half yearly pack'), ('365', 'yearly pack'), ('70', 'special pack 1')], default=28)),
                ('daily_internet', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
