# Generated by Django 4.1.4 on 2022-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.CharField(choices=[('28', 'month pack'), ('56', 'two months pack'), ('84', 'three months pack'), ('180', 'half yearly pack'), ('365', 'yearly pack'), ('70', 'special pack 1')], default=28, max_length=3),
        ),
    ]
